# Generated by Django 6.0.2 on 2026-03-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0032_migrate_action_plan_status_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceactionplan',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='action_plans', to='compliance.requirement', verbose_name='Linked requirements'),
        ),
    ]
