# Generated by Django 6.0.2 on 2026-04-17 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0034_add_compliance_status_choices'),
        ('reports', '0004_alter_historicalreport_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceactionplan',
            name='originating_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_action_plans', to='reports.managementreview', verbose_name='Originating management review'),
        ),
        migrations.AddField(
            model_name='historicalcomplianceactionplan',
            name='originating_review',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reports.managementreview', verbose_name='Originating management review'),
        ),
    ]
