# Generated by Django 6.0.6 on 2026-06-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0038_assessment_workflow_state_from_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='applicability_managed_by_risks',
            field=models.BooleanField(default=False, help_text="When enabled, each requirement's applicability is derived automatically from its linked risks: applicable when at least one active risk is linked, not applicable otherwise. The applicability fields then become read-only on requirements of this framework.", verbose_name='Risk-driven applicability'),
        ),
        migrations.AddField(
            model_name='historicalframework',
            name='applicability_managed_by_risks',
            field=models.BooleanField(default=False, help_text="When enabled, each requirement's applicability is derived automatically from its linked risks: applicable when at least one active risk is linked, not applicable otherwise. The applicability fields then become read-only on requirements of this framework.", verbose_name='Risk-driven applicability'),
        ),
    ]
