# Generated by Django 6.0.6 on 2026-06-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0039_framework_applicability_managed_by_risks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complianceactionplan',
            name='status',
        ),
        migrations.RemoveField(
            model_name='complianceassessment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalcomplianceactionplan',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalcomplianceassessment',
            name='status',
        ),
    ]
