# Generated by Django 6.0.6 on 2026-06-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0040_remove_complianceactionplan_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complianceactionplan',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='complianceactionplan',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='complianceactionplan',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='complianceassessment',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='complianceassessment',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='complianceassessment',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='framework',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='framework',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='framework',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='historicalcomplianceactionplan',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='historicalcomplianceactionplan',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='historicalcomplianceactionplan',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='historicalcomplianceassessment',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='historicalcomplianceassessment',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='historicalcomplianceassessment',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='historicalfinding',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='historicalfinding',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='historicalfinding',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='historicalframework',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='historicalframework',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='historicalframework',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='historicalrequirement',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='historicalrequirement',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='historicalrequirement',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='complianceactionplan',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AlterField(
            model_name='complianceassessment',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AlterField(
            model_name='framework',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceactionplan',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceassessment',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AlterField(
            model_name='historicalfinding',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AlterField(
            model_name='historicalframework',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AlterField(
            model_name='historicalrequirement',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
    ]
