# Generated by Django 6.0.6 on 2026-08-27 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0041_remove_complianceactionplan_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='effectiveness_reviewed_at',
            field=models.DateTimeField(blank=True, help_text="When the corrective action's effectiveness was reviewed.", null=True, verbose_name='Effectiveness reviewed at'),
        ),
        migrations.AddField(
            model_name='finding',
            name='effectiveness_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_findings', to=settings.AUTH_USER_MODEL, verbose_name='Effectiveness reviewed by'),
        ),
        migrations.AddField(
            model_name='finding',
            name='effectiveness_verdict',
            field=models.CharField(blank=True, choices=[('effective', 'Effective'), ('partially_effective', 'Partially effective'), ('not_effective', 'Not effective')], default='', help_text='Whether the corrective action worked. An action plan reaching a done step proves it was implemented, never that it was effective.', max_length=32, verbose_name='Effectiveness verdict'),
        ),
        migrations.AddField(
            model_name='finding',
            name='source',
            field=models.CharField(choices=[('audit', 'Audit'), ('incident', 'Security incident'), ('management_review', 'Management review'), ('monitoring', 'Monitoring'), ('complaint', 'Complaint')], db_index=True, default='audit', help_text='What surfaced this nonconformity.', max_length=32, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='historicalfinding',
            name='effectiveness_reviewed_at',
            field=models.DateTimeField(blank=True, help_text="When the corrective action's effectiveness was reviewed.", null=True, verbose_name='Effectiveness reviewed at'),
        ),
        migrations.AddField(
            model_name='historicalfinding',
            name='effectiveness_reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Effectiveness reviewed by'),
        ),
        migrations.AddField(
            model_name='historicalfinding',
            name='effectiveness_verdict',
            field=models.CharField(blank=True, choices=[('effective', 'Effective'), ('partially_effective', 'Partially effective'), ('not_effective', 'Not effective')], default='', help_text='Whether the corrective action worked. An action plan reaching a done step proves it was implemented, never that it was effective.', max_length=32, verbose_name='Effectiveness verdict'),
        ),
        migrations.AddField(
            model_name='historicalfinding',
            name='source',
            field=models.CharField(choices=[('audit', 'Audit'), ('incident', 'Security incident'), ('management_review', 'Management review'), ('monitoring', 'Monitoring'), ('complaint', 'Complaint')], db_index=True, default='audit', help_text='What surfaced this nonconformity.', max_length=32, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='assessment',
            field=models.ForeignKey(blank=True, help_text='The audit that raised this nonconformity, when one did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='compliance.complianceassessment', verbose_name='Assessment'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='assessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='findings', to=settings.AUTH_USER_MODEL, verbose_name='Raised by'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='recommendation',
            field=models.TextField(blank=True, default='', verbose_name='Recommendation'),
        ),
        migrations.AlterField(
            model_name='historicalfinding',
            name='assessment',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The audit that raised this nonconformity, when one did.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compliance.complianceassessment', verbose_name='Assessment'),
        ),
        migrations.AlterField(
            model_name='historicalfinding',
            name='assessor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Raised by'),
        ),
        migrations.AlterField(
            model_name='historicalfinding',
            name='recommendation',
            field=models.TextField(blank=True, default='', verbose_name='Recommendation'),
        ),
    ]
