# Generated by Django 6.0.6 on 2026-08-27 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0042_generalise_finding_to_nonconformity_register'),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='incident',
            field=models.ForeignKey(blank=True, help_text='The security incident that raised this nonconformity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='incidents.incident', verbose_name='Incident'),
        ),
        migrations.AddField(
            model_name='historicalfinding',
            name='incident',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The security incident that raised this nonconformity.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incidents.incident', verbose_name='Incident'),
        ),
    ]
