# Generated by Django 6.0.2 on 2026-06-15 09:31

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0032_remove_historicalscope_status_and_more'),
        ('trust_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Reference')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approval date')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('workflow_state', models.CharField(db_index=True, default='pending', max_length=32, verbose_name='Lifecycle state')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('requester_name', models.CharField(max_length=255, verbose_name='Name')),
                ('company', models.CharField(blank=True, default='', max_length=255, verbose_name='Company')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Reason')),
                ('nda_accepted', models.BooleanField(default=False, verbose_name='NDA accepted')),
                ('nda_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='NDA accepted at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User agent')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed at')),
                ('decision_note', models.TextField(blank=True, default='', verbose_name='Decision note')),
                ('download_token_issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Token issued at')),
                ('download_link_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Link expires at')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download count')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='trust_center.trustcenterdocument', verbose_name='Document')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_document_requests', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_set', to='context.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Document request',
                'verbose_name_plural': 'Document requests',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalDocumentRequest',
            fields=[
                ('reference', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Reference')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approval date')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('workflow_state', models.CharField(db_index=True, default='pending', max_length=32, verbose_name='Lifecycle state')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('requester_name', models.CharField(max_length=255, verbose_name='Name')),
                ('company', models.CharField(blank=True, default='', max_length=255, verbose_name='Company')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Reason')),
                ('nda_accepted', models.BooleanField(default=False, verbose_name='NDA accepted')),
                ('nda_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='NDA accepted at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User agent')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed at')),
                ('decision_note', models.TextField(blank=True, default='', verbose_name='Decision note')),
                ('download_token_issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Token issued at')),
                ('download_link_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Link expires at')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download count')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('document', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trust_center.trustcenterdocument', verbose_name='Document')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by')),
            ],
            options={
                'verbose_name': 'historical Document request',
                'verbose_name_plural': 'historical Document requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
