# Generated by Django 6.0.2 on 2026-06-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_center', '0002_documentrequest_historicaldocumentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustcentersettings',
            name='custom_css',
            field=models.TextField(blank=True, default='', help_text='Optional CSS injected into the public page to override the theme.', verbose_name='Custom CSS'),
        ),
    ]
