# Generated by Django 6.0.6 on 2026-06-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_center', '0003_trustcentersettings_custom_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrequest',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentrequest',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentrequest',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='historicaltrustcentercertification',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='historicaltrustcentercertification',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='historicaltrustcentercertification',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='historicaltrustcenterdocument',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='historicaltrustcenterdocument',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='historicaltrustcenterdocument',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='historicaltrustcentermeasure',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='historicaltrustcentermeasure',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='historicaltrustcentermeasure',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='historicaltrustcentersubprocessor',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='historicaltrustcentersubprocessor',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='historicaltrustcentersubprocessor',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='trustcentercertification',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='trustcentercertification',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='trustcentercertification',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='trustcenterdocument',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='trustcenterdocument',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='trustcenterdocument',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='trustcentermeasure',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='trustcentermeasure',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='trustcentermeasure',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='trustcentersubprocessor',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='trustcentersubprocessor',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='trustcentersubprocessor',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='historicaltrustcentercertification',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AlterField(
            model_name='historicaltrustcenterdocument',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AlterField(
            model_name='historicaltrustcentermeasure',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AlterField(
            model_name='historicaltrustcentersubprocessor',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AlterField(
            model_name='trustcentercertification',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AlterField(
            model_name='trustcenterdocument',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AlterField(
            model_name='trustcentermeasure',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AlterField(
            model_name='trustcentersubprocessor',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
    ]
