# Generated by Django 6.0.6 on 2026-06-26 01:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_backfill_workflow_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(db_index=True, max_length=64, verbose_name='Object id')),
                ('lifecycle_name', models.CharField(max_length=100, verbose_name='Lifecycle')),
                ('from_step', models.CharField(blank=True, default='', max_length=64, verbose_name='From step')),
                ('to_step', models.CharField(max_length=64, verbose_name='To step')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('form_data', models.JSONField(blank=True, default=dict, verbose_name='Form data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Performed at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_events', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type')),
            ],
            options={
                'verbose_name': 'Lifecycle event',
                'verbose_name_plural': 'Lifecycle events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', '-created_at'], name='core_lifecy_content_5e125e_idx')],
            },
        ),
    ]
