# Generated by Django 6.0.6 on 2026-07-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lifecycleevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VersioningConfig',
        ),
    ]
