# Generated by Django 6.0.6 on 2026-07-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_versioningconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text="Technical identifier a model binds to via LIFECYCLE_NAME, e.g. 'support_asset'.", max_length=100, unique=True, verbose_name='Lifecycle name')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Display name')),
                ('definition', models.JSONField(default=dict, help_text='Steps and transitions. Exactly one Draft step and at least one Archived step.', verbose_name='Definition (JSON)')),
                ('is_system', models.BooleanField(default=False, verbose_name='System lifecycle')),
                ('is_customized', models.BooleanField(default=False, verbose_name='Customized')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Lifecycle definition',
                'verbose_name_plural': 'Lifecycle definitions',
                'ordering': ['name'],
            },
        ),
    ]
