# Generated by Django 6.0.2 on 2026-03-26 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0021_swot_strategy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Users responsible for this scope. Managers automatically have access to this scope.', related_name='managed_scopes', to=settings.AUTH_USER_MODEL, verbose_name='Managers'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='collection_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('internal', 'Predefined Fairway')], default='manual', max_length=20, verbose_name='Collection method'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Predefined Fairway indicator'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='collection_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('internal', 'Predefined Fairway')], default='manual', max_length=20, verbose_name='Collection method'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Predefined Fairway indicator'),
        ),
    ]
