# Generated by Django 6.0.2 on 2026-04-17 11:30

import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0022_add_managers_to_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStakeholderFeedback',
            fields=[
                ('reference', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Reference')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approval date')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('channel', models.CharField(choices=[('survey', 'Survey'), ('meeting', 'Meeting'), ('complaint', 'Complaint'), ('email', 'Email'), ('audit', 'Audit'), ('incident', 'Incident'), ('other', 'Other')], max_length=20, verbose_name='Channel')),
                ('received_date', models.DateField(verbose_name='Received date')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content')),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('mixed', 'Mixed')], default='', max_length=20, verbose_name='Sentiment')),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='', max_length=20, verbose_name='Severity')),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under review'), ('addressed', 'Addressed'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='Status')),
                ('response', models.TextField(blank=True, default='', verbose_name='Response')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Stakeholder feedback',
                'verbose_name_plural': 'historical Stakeholder feedback',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StakeholderFeedback',
            fields=[
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Reference')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approval date')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('channel', models.CharField(choices=[('survey', 'Survey'), ('meeting', 'Meeting'), ('complaint', 'Complaint'), ('email', 'Email'), ('audit', 'Audit'), ('incident', 'Incident'), ('other', 'Other')], max_length=20, verbose_name='Channel')),
                ('received_date', models.DateField(verbose_name='Received date')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content')),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('mixed', 'Mixed')], default='', max_length=20, verbose_name='Sentiment')),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='', max_length=20, verbose_name='Severity')),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under review'), ('addressed', 'Addressed'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='Status')),
                ('response', models.TextField(blank=True, default='', verbose_name='Response')),
            ],
            options={
                'verbose_name': 'Stakeholder feedback',
                'verbose_name_plural': 'Stakeholder feedback',
                'abstract': False,
            },
        ),
    ]
