# Generated by Django 6.0.2 on 2026-04-17 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0023_historicalstakeholderfeedback_stakeholderfeedback'),
        ('reports', '0004_alter_historicalreport_report_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobjective',
            name='originating_review',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reports.managementreview', verbose_name='Originating management review'),
        ),
        migrations.AddField(
            model_name='objective',
            name='originating_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_objectives', to='reports.managementreview', verbose_name='Originating management review'),
        ),
        migrations.AddField(
            model_name='historicalstakeholderfeedback',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AddField(
            model_name='historicalstakeholderfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='historicalstakeholderfeedback',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstakeholderfeedback',
            name='stakeholder',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='context.stakeholder', verbose_name='Stakeholder'),
        ),
        migrations.AddField(
            model_name='stakeholderfeedback',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AddField(
            model_name='stakeholderfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='stakeholderfeedback',
            name='linked_expectations',
            field=models.ManyToManyField(blank=True, related_name='stakeholder_feedback', to='context.stakeholderexpectation', verbose_name='Linked expectations'),
        ),
        migrations.AddField(
            model_name='stakeholderfeedback',
            name='linked_issues',
            field=models.ManyToManyField(blank=True, related_name='stakeholder_feedback', to='context.issue', verbose_name='Linked issues'),
        ),
        migrations.AddField(
            model_name='stakeholderfeedback',
            name='scopes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='context.scope', verbose_name='Scopes'),
        ),
        migrations.AddField(
            model_name='stakeholderfeedback',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='context.stakeholder', verbose_name='Stakeholder'),
        ),
        migrations.AddField(
            model_name='stakeholderfeedback',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_set', to='context.tag', verbose_name='Tags'),
        ),
    ]
