# Generated by Django 6.0.2 on 2026-06-02

"""Add owner FK + linked_objectives / linked_requirements M2M to Indicator.

QA report CAIRN-IND-02: an indicator had no way to point at the objective
or requirement it actually measured, so the "indicator -> objective /
control" traceability required by ISO 27001 §6.2 / §9.1 was impossible.
owner is left nullable for now so existing rows survive the migration;
the MCP / DRF surface treats it as optional too. linked_objectives and
linked_requirements are M2M because a single indicator typically rolls
several KPIs together (e.g. "incident response time" tracks multiple
SLA requirements).

The verbose_name AlterField operations that makemigrations also produced
for collection_method / is_internal stem from the rebrand string changes
("Predefined Open GRC" -> "Predefined Cairn"). Intentionally excluded
here to keep the migration focused, just like in 0025.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0035_complianceactionplan_originating_review_and_more"),
        ("context", "0025_indicator_measurement_recorded_at_writable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalindicator",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Person accountable for the indicator's measurement and review.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Person accountable for the indicator's measurement and review.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_indicators",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="linked_objectives",
            field=models.ManyToManyField(
                blank=True,
                help_text="Objectives this indicator measures progress against (ISO 27001 §6.2 / §9.1).",
                related_name="indicators",
                to="context.objective",
                verbose_name="Linked objectives",
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="linked_requirements",
            field=models.ManyToManyField(
                blank=True,
                help_text="Compliance requirements this indicator measures the satisfaction of.",
                related_name="indicators",
                to="compliance.requirement",
                verbose_name="Linked requirements",
            ),
        ),
    ]
