# Generated by Django 6.0.2 on 2026-06-02

"""Cairn rebrand: refresh Indicator verbose_names that still say "Open GRC".

When the platform was renamed from Open GRC to Cairn (v0.24.0), the
Indicator model's `collection_method` choices and `is_internal`
verbose_name were updated in code ("Predefined Open GRC" -> "Predefined
Cairn") but no migration was generated at the time. Every subsequent
makemigrations dry-run kept reporting these as pending changes, and
the warning surfaced loudly at container boot. This migration captures
the AlterField operations so the rebrand stops haunting the diff.
Purely cosmetic: verbose_names do not affect the DB schema or query
output, only the admin labels.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0028_site_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicator',
            name='collection_method',
            field=models.CharField(
                choices=[('manual', 'Manual'), ('api', 'API'), ('internal', 'Predefined Cairn')],
                default='manual',
                max_length=20,
                verbose_name='Collection method',
            ),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Predefined Cairn indicator'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='collection_method',
            field=models.CharField(
                choices=[('manual', 'Manual'), ('api', 'API'), ('internal', 'Predefined Cairn')],
                default='manual',
                max_length=20,
                verbose_name='Collection method',
            ),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Predefined Cairn indicator'),
        ),
    ]
