# Generated by Django 6.0.2 on 2026-06-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0031_fold_publication_status_into_lifecycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalscope',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalsite',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalswotanalysis',
            name='status',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='status',
        ),
        migrations.RemoveField(
            model_name='site',
            name='status',
        ),
        migrations.RemoveField(
            model_name='swotanalysis',
            name='status',
        ),
    ]
