# Generated by Django 6.0.2 on 2026-06-01 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0027_update_supplier_dependency_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupportasset',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Supplier that provides, hosts or maintains this asset.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='supportasset',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier that provides, hosts or maintains this asset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_assets', to='assets.supplier', verbose_name='Supplier'),
        ),
    ]
