# Generated by Django 6.0.6 on 2026-06-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0037_migrate_supplier_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplier',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
