# Generated by Django 6.0.6 on 2026-06-28 20:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

REFERENCE_PREFIX = "CTRT-"


def upgrade_contracts(apps, schema_editor):
    """Promote legacy contracts to the BaseModel/ScopedModel shape.

    Runs after the new columns/M2M tables are added but before the unique
    constraint on ``reference``, so it can deduplicate references safely:
    - mirror the legacy ``status`` onto ``workflow_state``;
    - attach each contract to the union of its suppliers' scopes;
    - assign a unique ``CTRT-N`` reference to every contract whose reference is
      empty or duplicated (migration 0035 left many empty / non-unique).
    """
    Contract = apps.get_model("assets", "Contract")

    for c in Contract.objects.all():
        c.workflow_state = c.status or "draft"
        c.save(update_fields=["workflow_state"])

    for c in Contract.objects.all():
        scope_ids = set()
        for supplier in c.suppliers.all():
            scope_ids.update(supplier.scopes.values_list("id", flat=True))
        if scope_ids:
            c.scopes.add(*scope_ids)

    max_num = 0
    for c in Contract.objects.all():
        ref = c.reference or ""
        if ref.startswith(REFERENCE_PREFIX):
            try:
                max_num = max(max_num, int(ref[len(REFERENCE_PREFIX):]))
            except ValueError:
                pass

    seen = set()
    for c in Contract.objects.all().order_by("created_at"):
        ref = c.reference or ""
        if ref and ref not in seen:
            seen.add(ref)
            continue
        max_num += 1
        new_ref = f"{REFERENCE_PREFIX}{max_num}"
        c.reference = new_ref
        seen.add(new_ref)
        c.save(update_fields=["reference"])


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0039_remap_supplier_lifecycle_steps'),
        ('context', '0033_scope_lifecycle_steps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approval date'),
        ),
        migrations.AddField(
            model_name='contract',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AddField(
            model_name='contract',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='context.stakeholder', verbose_name='Clients'),
        ),
        migrations.AddField(
            model_name='contract',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Content type'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='contract',
            name='file_content',
            field=models.BinaryField(blank=True, null=True, verbose_name='File content'),
        ),
        migrations.AddField(
            model_name='contract',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='File name'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='contract',
            name='scopes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='context.scope', verbose_name='Scopes'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_set', to='context.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='contract',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='contract',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approval date'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Content type'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='File name'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.RunPython(upgrade_contracts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contract',
            name='reference',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='HistoricalContract_clients',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.contract')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.historicalcontract')),
                ('stakeholder', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='context.stakeholder')),
            ],
            options={
                'verbose_name': 'HistoricalContract_clients',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
