# Generated by Django 6.0.6 on 2026-06-29 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0040_contract_basemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='assets.contract', verbose_name='Cancels and replaces'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='supersedes',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.contract', verbose_name='Cancels and replaces'),
        ),
    ]
