# Generated by Django 6.0.6 on 2026-06-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0041_contract_supersedes_historicalcontract_supersedes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('under_review', 'Under review'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('under_review', 'Under review'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
