# Generated by Django 6.0.6 on 2026-06-29 08:44

from django.db import migrations, models


def rename_terminated_to_archived(apps, schema_editor):
    """The contract end-of-life step was renamed ``terminated`` -> ``archived``."""
    Contract = apps.get_model("assets", "Contract")
    Contract.objects.filter(status="terminated").update(status="archived")
    Contract.objects.filter(workflow_state="terminated").update(workflow_state="archived")


def rename_archived_to_terminated(apps, schema_editor):
    Contract = apps.get_model("assets", "Contract")
    Contract.objects.filter(status="archived").update(status="terminated")
    Contract.objects.filter(workflow_state="archived").update(workflow_state="terminated")


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0042_alter_contract_status_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_terminated_to_archived, rename_archived_to_terminated),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('drafting', 'Contract draft'), ('signing', 'Under signature'), ('active', 'In force'), ('under_review', 'Under review'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('drafting', 'Contract draft'), ('signing', 'Under signature'), ('active', 'In force'), ('under_review', 'Under review'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
