# Generated by Django 6.0.6 on 2026-06-29 13:29

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0043_alter_contract_status_and_more'),
        ('compliance', '0039_framework_applicability_managed_by_risks_and_more'),
        ('context', '0033_scope_lifecycle_steps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Reference')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approval date')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('workflow_state', models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state')),
                ('label', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('valid', 'Valid'), ('under_renewal', 'Under renewal'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('certificate_number', models.CharField(blank=True, default='', max_length=120, verbose_name='Certificate number')),
                ('issuer', models.CharField(blank=True, default='', max_length=255, verbose_name='Certification body')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry date')),
                ('scope_statement', models.TextField(blank=True, default='', verbose_name='Certified scope')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('file_content', models.BinaryField(blank=True, null=True, verbose_name='File content')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='File name')),
                ('content_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Content type')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('framework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='compliance.framework', verbose_name='Framework')),
                ('scopes', models.ManyToManyField(blank=True, related_name='%(class)s_set', to='context.scope', verbose_name='Scopes')),
                ('sites', models.ManyToManyField(blank=True, related_name='certificates', to='context.site', verbose_name='Covered sites')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='assets.certificate', verbose_name='Renews / replaces')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_set', to='context.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issue_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCertificate',
            fields=[
                ('reference', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Reference')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approval date')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('workflow_state', models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state')),
                ('label', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('valid', 'Valid'), ('under_renewal', 'Under renewal'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('certificate_number', models.CharField(blank=True, default='', max_length=120, verbose_name='Certificate number')),
                ('issuer', models.CharField(blank=True, default='', max_length=255, verbose_name='Certification body')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry date')),
                ('scope_statement', models.TextField(blank=True, default='', verbose_name='Certified scope')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='File name')),
                ('content_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Content type')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('framework', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compliance.framework', verbose_name='Framework')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.certificate', verbose_name='Renews / replaces')),
            ],
            options={
                'verbose_name': 'historical Certificate',
                'verbose_name_plural': 'historical Certificates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCertificate_sites',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.certificate')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.historicalcertificate')),
                ('site', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='context.site')),
            ],
            options={
                'verbose_name': 'HistoricalCertificate_sites',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
