# Generated by Django 6.0.6 on 2026-06-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0044_certificate_historicalcertificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('assessment', 'Assessment'), ('certified', 'Certified'), ('under_renewal', 'Under renewal'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('assessment', 'Assessment'), ('certified', 'Certified'), ('under_renewal', 'Under renewal'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
