# Generated by Django 6.0.6 on 2026-06-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0046_certificate_valid_to_certified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='status',
        ),
        migrations.RemoveField(
            model_name='essentialasset',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalcertificate',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalcontract',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalessentialasset',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalsupportasset',
            name='status',
        ),
        migrations.RemoveField(
            model_name='supportasset',
            name='status',
        ),
    ]
