# Generated by Django 6.0.6 on 2026-07-08 08:57

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0048_remove_assetdependency_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplier',
            name='parent_company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The parent company this supplier is a subsidiary of.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.supplier', verbose_name='Parent company'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='parent_company',
            field=models.ForeignKey(blank=True, help_text='The parent company this supplier is a subsidiary of.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='assets.supplier', verbose_name='Parent company'),
        ),
        migrations.CreateModel(
            name='HistoricalSupplierSubprocessor',
            fields=[
                ('reference', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Reference')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('purpose', models.CharField(blank=True, default='', help_text='Nature of the service delegated to the sub-processor.', max_length=500, verbose_name='Purpose')),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Criticality')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subprocessor', models.ForeignKey(blank=True, db_constraint=False, help_text='The supplier engaged as a sub-processor.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.supplier', verbose_name='Sub-processor')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, help_text='The supplier (délégataire) that engages the sub-processor.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'historical Sub-processor',
                'verbose_name_plural': 'historical Sub-processors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SupplierSubprocessor',
            fields=[
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Reference')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(blank=True, default='', help_text='Nature of the service delegated to the sub-processor.', max_length=500, verbose_name='Purpose')),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Criticality')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_subprocessors', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('subprocessor', models.ForeignKey(help_text='The supplier engaged as a sub-processor.', on_delete=django.db.models.deletion.PROTECT, related_name='engaged_by', to='assets.supplier', verbose_name='Sub-processor')),
                ('supplier', models.ForeignKey(help_text='The supplier (délégataire) that engages the sub-processor.', on_delete=django.db.models.deletion.CASCADE, related_name='subprocessors', to='assets.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Sub-processor',
                'verbose_name_plural': 'Sub-processors',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'subprocessor'), name='unique_supplier_subprocessor'), models.CheckConstraint(condition=models.Q(('supplier', models.F('subprocessor')), _negated=True), name='supplier_subprocessor_not_self')],
            },
        ),
    ]
