# Generated by Django 6.0.2 on 2026-04-17 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_historicalreport_report_type_and_more'),
        ('risks', '0014_alter_historicalriskcriteria_risk_matrix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrisktreatmentplan',
            name='originating_review',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reports.managementreview', verbose_name='Originating management review'),
        ),
        migrations.AddField(
            model_name='risktreatmentplan',
            name='originating_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_treatment_plans', to='reports.managementreview', verbose_name='Originating management review'),
        ),
    ]
