# Generated by Django 6.0.2 on 2026-06-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0030_fold_criteria_status_into_lifecycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalriskcriteria',
            name='status',
        ),
        migrations.RemoveField(
            model_name='riskcriteria',
            name='status',
        ),
    ]
