# Generated by Django 6.0.6 on 2026-06-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0031_remove_historicalriskcriteria_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baselinegap',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ebiossummary',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ebiosworkshopprogress',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalbaselinegap',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalebiossummary',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalebiosworkshopprogress',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalpacsmeasure',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalrisk',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalriskacceptance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalriskassessment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalrisktreatmentplan',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalsecuritybaseline',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalstudyframework',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalvulnerability',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pacsmeasure',
            name='status',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='status',
        ),
        migrations.RemoveField(
            model_name='riskacceptance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='risktreatmentplan',
            name='status',
        ),
        migrations.RemoveField(
            model_name='securitybaseline',
            name='status',
        ),
        migrations.RemoveField(
            model_name='studyframework',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='status',
        ),
    ]
