# Generated by Django 6.0.2 on 2026-03-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_add_impersonate_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('human', 'Human'), ('robot', 'Robot')], default='human', max_length=10, verbose_name='User type'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Successful login'), ('login_failed', 'Failed login'), ('logout', 'Logout'), ('token_refresh', 'Token refresh'), ('password_change', 'Password change'), ('account_locked', 'Account locked'), ('account_unlocked', 'Account unlocked'), ('passkey_login_success', 'Passkey login'), ('passkey_login_failed', 'Passkey login failed'), ('passkey_registered', 'Passkey registered'), ('passkey_deleted', 'Passkey deleted'), ('impersonation_start', 'Impersonation started'), ('impersonation_stop', 'Impersonation stopped')], db_index=True, max_length=30, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='First name'),
        ),
    ]
