# Generated by Django 6.0.2 on 2026-06-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_add_trust_center_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lifecycle_submitted', 'Element pending validation'), ('trust_document_requested', 'Trust Center document request')], db_index=True, max_length=50, verbose_name='Type'),
        ),
    ]
