# Generated by Django 6.0.2 on 2026-06-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collapsed_sections',
            field=models.JSONField(blank=True, default=list, help_text="Keys of collapsible UI sections the user has collapsed (e.g. the dashboard's Today's actions card).", verbose_name='Collapsed sections'),
        ),
    ]
