# Generated by Django 6.0.2 on 2026-06-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_user_collapsed_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='use_logo_as_app_brand',
            field=models.BooleanField(default=False, help_text='Replace the Cairn logo with the company logo across the application (the sidebar and page headers). The About dialog always keeps the Cairn logo.', verbose_name='Use the company logo as the application logo'),
        ),
    ]
