# Generated by Django 6.0.2 on 2026-06-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_companysettings_use_logo_as_app_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='app_name',
            field=models.CharField(blank=True, default='', help_text='Custom name shown in the sidebar and the browser tab titles. Defaults to Cairn when left empty.', max_length=100, verbose_name='Application name'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='use_logo_as_app_brand',
            field=models.BooleanField(default=False, help_text='Replace the Cairn logo in the sidebar with the company logo. The About dialog always keeps the Cairn logo.', verbose_name='Use the company logo as the application logo'),
        ),
    ]
