# Generated by Django 6.0.2 on 2026-06-18 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_companysettings_app_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='Hex colour (e.g. #1E3A8A) used as the accent throughout the application. Defaults to the Cairn navy when left empty.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', message='Enter a colour as a 6-digit hex code, e.g. #1E3A8A.')], verbose_name='Accent colour'),
        ),
    ]
