# Generated by Django 6.0.6 on 2026-06-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_user_dashboard_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='assistant_name',
            field=models.CharField(blank=True, default='', help_text='Custom name for the AI assistant, shown in the command palette, its answers and the sidebar. Defaults to Ask Cairn when left empty.', max_length=100, verbose_name='Assistant name'),
        ),
    ]
