# Generated by Django 6.0.6 on 2026-06-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_companysettings_assistant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='column_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Per-view column layout: {view_key: {order: [...], hidden: [...]}}.', verbose_name='Column preferences'),
        ),
    ]
