# Generated by Django 6.0.6 on 2026-06-25 10:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_user_column_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('view_key', models.CharField(db_index=True, max_length=100, verbose_name='List')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('query', models.TextField(blank=True, default='', verbose_name='Query string')),
                ('is_shared', models.BooleanField(default=False, verbose_name='Shared with everyone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Saved filter',
                'verbose_name_plural': 'Saved filters',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'view_key', 'name'), name='uniq_saved_filter_owner_view_name')],
            },
        ),
    ]
