# Generated by Django 6.0.6 on 2026-07-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_add_data_import_override_dates_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Successful login'), ('login_failed', 'Failed login'), ('logout', 'Logout'), ('token_refresh', 'Token refresh'), ('password_change', 'Password change'), ('account_locked', 'Account locked'), ('account_unlocked', 'Account unlocked'), ('passkey_login_success', 'Passkey login'), ('passkey_login_failed', 'Passkey login failed'), ('passkey_registered', 'Passkey registered'), ('passkey_deleted', 'Passkey deleted'), ('impersonation_start', 'Impersonation started'), ('impersonation_stop', 'Impersonation stopped'), ('user_invited', 'User invited'), ('account_activated', 'Account activated')], db_index=True, max_length=30, verbose_name='Event type'),
        ),
    ]
