"""Tests for the company Certificate entity (Documents)."""

import datetime

import pytest
from django.core.files.uploadedfile import SimpleUploadedFile
from django.urls import reverse

from accounts.tests.factories import UserFactory
from assets.constants import CertificateStatus
from assets.forms import CertificateCreateForm
from assets.models import Certificate
from assets.tests.factories import CertificateFactory
from compliance.tests.factories import FrameworkFactory
from context.models import Site
from context.tests.factories import ScopeFactory

_PDF_BYTES = b"%PDF-1.4\n%fake minimal pdf\n"


def _data(response):
    """Extract payload, handling the StandardJSONRenderer envelope."""
    body = response.json()
    if isinstance(body, dict) and body.get("status") == "success" and "data" in body:
        return body["data"]
    return body


def _make_site(name="Datacenter Paris"):
    return Site.objects.create(name=name)


@pytest.mark.django_db
class TestCertificateModel:
    def test_str_and_sites(self):
        site = _make_site()
        c = Certificate.objects.create(label="ISO 27001 cert", reference="CERT-1")
        c.sites.add(site)
        assert str(c) == "ISO 27001 cert"
        assert c.sites.count() == 1
        assert c in site.certificates.all()
        assert c.site_names == [site.name]

    def test_framework_label_uses_short_name(self):
        fw = FrameworkFactory(name="ISO/IEC 27001", short_name="ISO 27001")
        c = Certificate.objects.create(label="cert", framework=fw)
        assert c.framework_label == "ISO 27001"
        # Falls back to the full name when there is no abbreviation.
        fw2 = FrameworkFactory(name="Health Data Hosting", short_name="")
        c2 = Certificate.objects.create(label="cert2", framework=fw2)
        assert c2.framework_label == "Health Data Hosting"
        # No framework -> empty label, no crash.
        assert Certificate.objects.create(label="cert3").framework_label == ""

    def test_is_expired(self):
        today = datetime.date.today()
        past = Certificate.objects.create(status="valid", expiry_date=today - datetime.timedelta(days=1))
        future = Certificate.objects.create(status="valid", expiry_date=today + datetime.timedelta(days=1))
        archived = Certificate.objects.create(status="archived", expiry_date=today - datetime.timedelta(days=1))
        assert past.is_expired is True
        assert future.is_expired is False
        assert archived.is_expired is False  # archived certificates do not "expire"


@pytest.mark.django_db
class TestCertificateLifecycle:
    def test_reference_autogenerated(self):
        c = Certificate.objects.create(label="Auto ref")
        assert c.reference.startswith("CERT-")

    def test_lifecycle_name_and_initial_step(self):
        c = Certificate.objects.create(label="WF", status=CertificateStatus.DRAFT)
        assert c.get_lifecycle().name == "certificate"
        assert c.workflow_state == "draft"

    def test_available_transitions_from_draft(self):
        c = Certificate.objects.create(label="WF", status=CertificateStatus.DRAFT)
        assert {t.target for t in c.available_transitions()} == {"valid", "archived"}

    def test_recertification_and_suspension_cycle(self):
        c = Certificate.objects.create(label="WF", status=CertificateStatus.DRAFT)
        c.transition_to("valid")  # Issue
        c.refresh_from_db()
        assert c.workflow_state == "valid"
        assert c.status == "valid"  # legacy status kept in sync
        targets = {t.target for t in c.available_transitions()}
        assert targets == {"under_renewal", "suspended", "expired", "archived"}
        # Recertification loop.
        c.transition_to("under_renewal")
        assert "valid" in {t.target for t in c.available_transitions()}
        c.transition_to("valid")
        # Suspension loop.
        c.transition_to("suspended")
        assert "valid" in {t.target for t in c.available_transitions()}
        c.transition_to("valid")
        c.refresh_from_db()
        assert c.workflow_state == "valid"

    def test_archive_from_any_state_without_comment(self):
        for start in ["valid", "under_renewal", "suspended", "expired"]:
            c = Certificate.objects.create(label=f"WF {start}", status=start)
            assert "archived" in {t.target for t in c.available_transitions()}
            c.transition_to("archived")  # no comment provided
            c.refresh_from_db()
            assert c.workflow_state == "archived"
            assert c.status == "archived"

    def test_archive_via_transition_endpoint(self, client):
        client.force_login(UserFactory(is_superuser=True, is_staff=True))
        c = CertificateFactory(status="valid", scopes=[ScopeFactory()])
        url = reverse(
            "workflow:transition",
            kwargs={"app_label": "assets", "model": "certificate", "pk": c.pk},
        )
        resp = client.post(url, {"target_status": "archived"})
        assert resp.status_code == 302
        c.refresh_from_db()
        assert c.workflow_state == "archived"
        assert c.status == "archived"

    def test_expired_cannot_be_renewed_in_place(self):
        from core.lifecycle import IllegalTransitionError

        c = Certificate.objects.create(label="WF", status="expired")
        with pytest.raises(IllegalTransitionError):
            c.transition_to("valid")
        assert {t.target for t in c.available_transitions()} == {"archived"}

    def test_illegal_transition_raises(self):
        from core.lifecycle import IllegalTransitionError

        c = Certificate.objects.create(label="WF", status=CertificateStatus.DRAFT)
        with pytest.raises(IllegalTransitionError):
            c.transition_to("under_renewal")  # draft must go through "valid" first

    def test_draft_is_deletable_valid_is_not(self):
        from core.workflow import LifecycleProtectedError

        draft = Certificate.objects.create(label="D", status=CertificateStatus.DRAFT)
        draft.delete()  # allowed
        valid = Certificate.objects.create(label="V", status=CertificateStatus.VALID)
        with pytest.raises(LifecycleProtectedError):
            valid.delete()


@pytest.mark.django_db
class TestCertificateForm:
    def test_framework_is_required(self):
        scope = ScopeFactory()
        form = CertificateCreateForm(
            user=UserFactory(is_superuser=True),
            data={"label": "X", "status": "draft", "scopes": [str(scope.pk)]},
        )
        assert not form.is_valid()
        assert "framework" in form.errors

    def test_expiry_before_issue_rejected(self):
        scope = ScopeFactory()
        fw = FrameworkFactory()
        form = CertificateCreateForm(
            user=UserFactory(is_superuser=True),
            data={"label": "X", "framework": str(fw.pk),
                  "status": "valid", "scopes": [str(scope.pk)],
                  "issue_date": "2025-01-01", "expiry_date": "2024-01-01"},
        )
        assert not form.is_valid()
        assert "expiry_date" in form.errors

    def test_supersedes_queryset_excludes_self(self):
        c = CertificateFactory()
        form = CertificateCreateForm(user=UserFactory(is_superuser=True), instance=c)
        assert c not in list(form.fields["supersedes"].queryset)


@pytest.mark.django_db
class TestCertificateCreateView:
    def _login(self, client):
        client.force_login(UserFactory(is_superuser=True, is_staff=True))

    def _base_data(self, scope):
        return {"label": "ISO 27001", "framework": str(FrameworkFactory().pk),
                "status": "draft", "scopes": [str(scope.pk)]}

    def test_scope_is_required(self, client):
        self._login(client)
        resp = client.post(reverse("assets:certificate-create"),
                           {"label": "X", "framework": str(FrameworkFactory().pk), "status": "draft"})
        assert resp.status_code == 200  # re-rendered with errors
        assert Certificate.objects.count() == 0

    def test_rejects_non_pdf_extension(self, client):
        self._login(client)
        scope = ScopeFactory()
        upload = SimpleUploadedFile("c.txt", _PDF_BYTES, content_type="text/plain")
        data = {**self._base_data(scope), "upload": upload}
        resp = client.post(reverse("assets:certificate-create"), data)
        assert resp.status_code == 200
        assert Certificate.objects.count() == 0

    def test_rejects_bad_magic_bytes(self, client):
        self._login(client)
        scope = ScopeFactory()
        upload = SimpleUploadedFile("c.pdf", b"NOT-A-PDF", content_type="application/pdf")
        data = {**self._base_data(scope), "upload": upload}
        resp = client.post(reverse("assets:certificate-create"), data)
        assert resp.status_code == 200
        assert Certificate.objects.count() == 0

    def test_accepts_valid_pdf(self, client):
        self._login(client)
        scope = ScopeFactory()
        upload = SimpleUploadedFile("c.pdf", _PDF_BYTES, content_type="application/pdf")
        data = {**self._base_data(scope), "upload": upload}
        resp = client.post(reverse("assets:certificate-create"), data)
        assert resp.status_code == 302
        certificate = Certificate.objects.get()
        assert certificate.has_document
        assert certificate.file_name == "c.pdf"
        assert certificate.get_file_bytes() == _PDF_BYTES
        assert list(certificate.scopes.all()) == [scope]

    def test_create_without_document(self, client):
        self._login(client)
        scope = ScopeFactory()
        resp = client.post(reverse("assets:certificate-create"), self._base_data(scope))
        assert resp.status_code == 302
        assert Certificate.objects.get().has_document is False


@pytest.mark.django_db
class TestCertificatePermissions:
    def test_list_redirects_without_permission(self, client):
        client.force_login(UserFactory())  # no perms
        resp = client.get(reverse("assets:certificate-list"))
        assert resp.status_code == 302  # web denial redirects

    def test_list_ok_for_superuser(self, client):
        client.force_login(UserFactory(is_superuser=True, is_staff=True))
        assert client.get(reverse("assets:certificate-list")).status_code == 200

    def test_list_header_has_breadcrumb(self, client):
        client.force_login(UserFactory(is_superuser=True, is_staff=True))
        resp = client.get(reverse("assets:certificate-list"))
        assert b"page-header__breadcrumb" in resp.content

    def test_detail_renders_with_lifecycle_stepper(self, client):
        client.force_login(UserFactory(is_superuser=True, is_staff=True))
        site = _make_site()
        certificate = CertificateFactory(sites=[site], scopes=[ScopeFactory()])
        resp = client.get(reverse("assets:certificate-detail", kwargs={"pk": certificate.pk}))
        assert resp.status_code == 200
        assert site.name.encode() in resp.content
        # The lifecycle renders with the standardised directed-graph stepper.
        assert b"data-lc-edges" in resp.content


@pytest.mark.django_db
class TestCertificateDocumentDownload:
    def _cert_with_pdf(self, scope=None):
        c = CertificateFactory(scopes=[scope] if scope else [])
        c.file_content = _PDF_BYTES
        c.file_name = "iso27001.pdf"
        c.content_type = "application/pdf"
        c.save()
        return c

    def test_download_requires_login(self, client):
        c = self._cert_with_pdf()
        resp = client.get(reverse("assets:certificate-document", kwargs={"pk": c.pk}))
        assert resp.status_code == 302  # redirected to login

    def test_download_returns_pdf(self, client):
        client.force_login(UserFactory(is_superuser=True, is_staff=True))
        c = self._cert_with_pdf()
        resp = client.get(reverse("assets:certificate-document", kwargs={"pk": c.pk}))
        assert resp.status_code == 200
        assert resp["Content-Type"] == "application/pdf"
        assert "iso27001.pdf" in resp["Content-Disposition"]
        assert resp.getvalue() == _PDF_BYTES

    def test_download_404_without_document(self, client):
        client.force_login(UserFactory(is_superuser=True, is_staff=True))
        c = CertificateFactory()
        resp = client.get(reverse("assets:certificate-document", kwargs={"pk": c.pk}))
        assert resp.status_code == 404

    def test_download_scope_restricted(self, client):
        from accounts.models import Group, Permission

        scope_a = ScopeFactory()
        scope_b = ScopeFactory()
        reader = UserFactory()
        grp = Group.objects.create(name="ScopedCertReaders")
        grp.permissions.add(Permission.objects.get(codename="assets.certificate.read"))
        grp.allowed_scopes.add(scope_a)
        grp.users.add(reader)
        client.force_login(reader)

        in_scope = self._cert_with_pdf(scope=scope_a)
        out_scope = self._cert_with_pdf(scope=scope_b)
        assert client.get(reverse("assets:certificate-document", kwargs={"pk": in_scope.pk})).status_code == 200
        assert client.get(reverse("assets:certificate-document", kwargs={"pk": out_scope.pk})).status_code == 404


@pytest.mark.django_db
class TestCertificateAPI:
    def _client(self):
        from rest_framework.test import APIClient

        api = APIClient()
        api.force_authenticate(user=UserFactory(is_superuser=True))
        return api

    def test_api_create_and_list(self):
        api = self._client()
        scope = ScopeFactory()
        fw = FrameworkFactory(name="ISO/IEC 27001", short_name="ISO 27001")
        resp = api.post(
            "/api/v1/assets/certificates/",
            {"label": "API ISO", "framework": str(fw.pk), "status": "draft",
             "scopes": [str(scope.pk)]},
            format="json",
        )
        assert resp.status_code == 201, resp.json()
        data = _data(resp)
        assert data["reference"].startswith("CERT-")
        assert data["framework_label"] == "ISO 27001"
        assert "file_content" not in data  # bytes never exposed

        listed = api.get("/api/v1/assets/certificates/")
        assert listed.status_code == 200

    def test_api_document_url_present_when_attached(self):
        api = self._client()
        c = CertificateFactory()
        c.file_content = _PDF_BYTES
        c.file_name = "x.pdf"
        c.save()
        resp = api.get(f"/api/v1/assets/certificates/{c.pk}/")
        assert resp.status_code == 200
        assert _data(resp)["document_url"].endswith(f"/certificates/{c.pk}/document/")

    def test_api_filter_by_framework(self):
        api = self._client()
        fw = FrameworkFactory()
        CertificateFactory(framework=fw)
        CertificateFactory()
        resp = api.get(f"/api/v1/assets/certificates/?framework={fw.pk}")
        assert resp.status_code == 200


@pytest.mark.django_db
class TestCertificateSupersede:
    def test_supersedes_relationship(self):
        old = CertificateFactory()
        new = CertificateFactory(supersedes=old)
        assert new.supersedes == old
        assert old.is_superseded is True
        assert new.is_superseded is False
        assert list(old.superseded_by.all()) == [new]

    def test_supersedes_set_null_on_replacement_delete(self):
        old = CertificateFactory(status=CertificateStatus.DRAFT)
        new = CertificateFactory(status=CertificateStatus.DRAFT, supersedes=old)
        old.delete()  # draft -> deletable; SET_NULL keeps the survivor
        new.refresh_from_db()
        assert new.supersedes is None

    def test_detail_shows_supersede_both_directions(self, client):
        client.force_login(UserFactory(is_superuser=True, is_staff=True))
        old = CertificateFactory(reference="CERT-200", label="Old cert")
        new = CertificateFactory(reference="CERT-201", label="New cert", supersedes=old)
        resp_old = client.get(reverse("assets:certificate-detail", kwargs={"pk": old.pk}))
        assert b"CERT-201" in resp_old.content  # replaced by
        resp_new = client.get(reverse("assets:certificate-detail", kwargs={"pk": new.pk}))
        assert b"CERT-200" in resp_new.content  # renews and replaces


@pytest.mark.django_db
class TestCertificateMCPRegistered:
    def test_certificate_tools_registered(self):
        from mcp.server import McpServer
        from mcp.tools import register_all_tools

        server = McpServer()
        register_all_tools(server)
        for name in ["list_certificates", "get_certificate", "create_certificate",
                     "update_certificate", "delete_certificate", "transition_certificate",
                     "certificate_allowed_transitions"]:
            assert name in server._tools
