"""Tests for the autonomous Contract entity and its supplier-detail display."""

import datetime

import pytest
from django.core.files.uploadedfile import SimpleUploadedFile
from django.urls import reverse

from accounts.tests.factories import UserFactory
from assets.constants import ContractStatus
from assets.forms import ContractCreateForm
from assets.models import Contract
from assets.tests.factories import ContractFactory, SupplierFactory
from context.constants import InfluenceLevel, IssueType, StakeholderCategory
from context.models import Stakeholder
from context.tests.factories import ScopeFactory


def _make_stakeholder(category):
    return Stakeholder.objects.create(
        name=f"Stakeholder {category}",
        type=IssueType.EXTERNAL,
        category=category,
        influence_level=InfluenceLevel.MEDIUM,
        interest_level=InfluenceLevel.MEDIUM,
    )


_PDF_BYTES = b"%PDF-1.4\n%fake minimal pdf\n"


def _data(response):
    """Extract payload, handling the StandardJSONRenderer wrapper (or a bare body
    when a ``status`` field defeats the envelope sentinel)."""
    body = response.json()
    if isinstance(body, dict) and body.get("status") == "success" and "data" in body:
        return body["data"]
    return body


@pytest.mark.django_db
class TestContractModel:
    def test_multi_party_and_str(self):
        a = SupplierFactory(name="Acme")
        b = SupplierFactory(name="Globex")
        c = Contract.objects.create(label="Joint MSA", reference="CTR-1")
        c.suppliers.add(a, b)
        assert c.suppliers.count() == 2
        assert str(c) == "Joint MSA"
        # reachable from each party
        assert c in a.contracts.all()
        assert c in b.contracts.all()

    def test_amendment_parent_relation(self):
        s = SupplierFactory()
        parent = Contract.objects.create(label="MSA")
        parent.suppliers.add(s)
        amend = Contract.objects.create(label="Avenant 1", parent=parent)
        amend.suppliers.add(s)
        assert amend.is_amendment is True
        assert parent.is_amendment is False
        assert list(parent.amendments.all()) == [amend]

    def test_is_expired(self):
        today = datetime.date.today()
        past = Contract.objects.create(status="active", end_date=today - datetime.timedelta(days=1))
        future = Contract.objects.create(status="active", end_date=today + datetime.timedelta(days=1))
        archived = Contract.objects.create(status="archived", end_date=today - datetime.timedelta(days=1))
        assert past.is_expired is True
        assert future.is_expired is False
        assert archived.is_expired is False  # only in-force contracts expire


@pytest.mark.django_db
class TestSupplierDetailContracts:
    def test_only_top_level_contracts_in_context(self, client):
        from accounts.tests.factories import UserFactory

        client.force_login(UserFactory(is_superuser=True, is_staff=True))
        s = SupplierFactory()
        top = Contract.objects.create(label="MSA")
        top.suppliers.add(s)
        amend = Contract.objects.create(label="Avenant", parent=top)
        amend.suppliers.add(s)
        resp = client.get(reverse("assets:supplier-detail", kwargs={"pk": s.pk}))
        assert resp.status_code == 200
        contracts = list(resp.context["contracts"])
        assert top in contracts
        assert amend not in contracts  # amendments are nested, not top-level cards


@pytest.mark.django_db
class TestContractLifecycle:
    def test_reference_autogenerated(self):
        c = Contract.objects.create(label="Auto ref")
        assert c.reference.startswith("CTRT-")

    def test_lifecycle_name_and_initial_step(self):
        c = Contract.objects.create(label="WF", status=ContractStatus.DRAFT)
        assert c.get_lifecycle().name == "contract"
        assert c.workflow_state == "draft"

    def test_available_transitions_from_draft(self):
        # Draft (generic entry) is distinct from "Contract draft": the first
        # move is into drafting; archive is always available.
        c = Contract.objects.create(label="WF", status=ContractStatus.DRAFT)
        targets = {t.target for t in c.available_transitions()}
        assert targets == {"drafting", "archived"}

    def test_entry_chain_and_review_cycle(self):
        c = Contract.objects.create(label="WF", status=ContractStatus.DRAFT)
        c.transition_to("drafting")   # Start drafting
        c.transition_to("signing")    # Send for signature
        c.transition_to("active")     # Bring into force
        c.refresh_from_db()
        assert c.workflow_state == "active"
        assert c.status == "active"  # legacy status kept in sync
        # In force <-> Under review recurring cycle.
        assert {t.target for t in c.available_transitions()} == {"under_review", "expired", "archived"}
        c.transition_to("under_review")
        assert "active" in {t.target for t in c.available_transitions()}  # Reviewed
        c.transition_to("active")
        c.refresh_from_db()
        assert c.workflow_state == "active"

    def test_archive_from_any_state_without_comment(self):
        # The lifecycle stepper UI collects no comment, so Archive must not be
        # comment-gated (otherwise the transition silently fails).
        for start in ["drafting", "signing", "active", "expired"]:
            c = Contract.objects.create(label=f"WF {start}", status=start)
            assert "archived" in {t.target for t in c.available_transitions()}
            c.transition_to("archived")  # no comment provided
            c.refresh_from_db()
            assert c.workflow_state == "archived"
            assert c.status == "archived"

    def test_archive_via_transition_endpoint(self, client):
        # Reproduce the stepper action: the lifecycle form POSTs target_status
        # only (no comment). Archive must move the contract to archived.
        client.force_login(UserFactory(is_superuser=True, is_staff=True))
        c = ContractFactory(status="active", scopes=[ScopeFactory()])
        url = reverse(
            "workflow:transition",
            kwargs={"app_label": "assets", "model": "contract", "pk": c.pk},
        )
        resp = client.post(url, {"target_status": "archived"})
        assert resp.status_code == 302
        c.refresh_from_db()
        assert c.workflow_state == "archived"
        assert c.status == "archived"

    def test_expired_cannot_be_renewed_in_place(self):
        from core.lifecycle import IllegalTransitionError

        c = Contract.objects.create(label="WF", status="expired")
        # No expired -> active : an expired contract is replaced (supersedes).
        with pytest.raises(IllegalTransitionError):
            c.transition_to("active")
        assert {t.target for t in c.available_transitions()} == {"archived"}

    def test_illegal_transition_raises(self):
        from core.lifecycle import IllegalTransitionError

        c = Contract.objects.create(label="WF", status=ContractStatus.DRAFT)
        with pytest.raises(IllegalTransitionError):
            c.transition_to("active")  # draft must go through "signing" first

    def test_draft_is_deletable_active_is_not(self):
        from core.lifecycle import LifecycleProtectedError

        draft = Contract.objects.create(label="D", status=ContractStatus.DRAFT)
        draft.delete()  # allowed
        active = Contract.objects.create(label="A", status=ContractStatus.ACTIVE)
        with pytest.raises(LifecycleProtectedError):
            active.delete()


@pytest.mark.django_db
class TestContractForm:
    def test_clients_queryset_only_customers(self):
        customer = _make_stakeholder(StakeholderCategory.CUSTOMERS)
        supplier_sh = _make_stakeholder(StakeholderCategory.SUPPLIERS)
        form = ContractCreateForm(user=UserFactory(is_superuser=True))
        clients = list(form.fields["clients"].queryset)
        assert customer in clients
        assert supplier_sh not in clients

    def test_parent_queryset_excludes_self_and_amendments(self):
        top = ContractFactory()
        amendment = ContractFactory(parent=top)
        form = ContractCreateForm(user=UserFactory(is_superuser=True), instance=top)
        parents = list(form.fields["parent"].queryset)
        assert top not in parents          # never itself
        assert amendment not in parents    # amendments cannot be parents


@pytest.mark.django_db
class TestContractCreateView:
    def _login(self, client):
        client.force_login(UserFactory(is_superuser=True, is_staff=True))

    def _base_data(self, scope):
        return {"label": "MSA", "status": "draft", "scopes": [str(scope.pk)], "currency": ""}

    def test_scope_is_required(self, client):
        self._login(client)
        resp = client.post(reverse("assets:contract-create"), {"label": "X", "status": "draft"})
        assert resp.status_code == 200  # re-rendered with errors
        assert Contract.objects.count() == 0

    def test_rejects_non_pdf_extension(self, client):
        self._login(client)
        scope = ScopeFactory()
        upload = SimpleUploadedFile("c.txt", _PDF_BYTES, content_type="text/plain")
        data = {**self._base_data(scope), "upload": upload}
        resp = client.post(reverse("assets:contract-create"), data)
        assert resp.status_code == 200
        assert Contract.objects.count() == 0

    def test_rejects_bad_magic_bytes(self, client):
        self._login(client)
        scope = ScopeFactory()
        upload = SimpleUploadedFile("c.pdf", b"NOT-A-PDF", content_type="application/pdf")
        data = {**self._base_data(scope), "upload": upload}
        resp = client.post(reverse("assets:contract-create"), data)
        assert resp.status_code == 200
        assert Contract.objects.count() == 0

    def test_accepts_valid_pdf(self, client):
        self._login(client)
        scope = ScopeFactory()
        upload = SimpleUploadedFile("c.pdf", _PDF_BYTES, content_type="application/pdf")
        data = {**self._base_data(scope), "upload": upload}
        resp = client.post(reverse("assets:contract-create"), data)
        assert resp.status_code == 302
        contract = Contract.objects.get()
        assert contract.has_document
        assert contract.file_name == "c.pdf"
        assert contract.get_file_bytes() == _PDF_BYTES
        assert list(contract.scopes.all()) == [scope]

    def test_create_without_document(self, client):
        self._login(client)
        scope = ScopeFactory()
        resp = client.post(reverse("assets:contract-create"), self._base_data(scope))
        assert resp.status_code == 302
        assert Contract.objects.get().has_document is False


@pytest.mark.django_db
class TestContractPermissions:
    def test_list_redirects_without_permission(self, client):
        client.force_login(UserFactory())  # no perms
        resp = client.get(reverse("assets:contract-list"))
        assert resp.status_code == 302  # web denial redirects

    def test_list_ok_for_superuser(self, client):
        client.force_login(UserFactory(is_superuser=True, is_staff=True))
        assert client.get(reverse("assets:contract-list")).status_code == 200

    def test_list_header_has_breadcrumb(self, client):
        # The header must render the breadcrumb (Assets > Documents > Contracts),
        # like every other list page (NAV_TREE registration).
        client.force_login(UserFactory(is_superuser=True, is_staff=True))
        resp = client.get(reverse("assets:contract-list"))
        assert b"page-header__breadcrumb" in resp.content

    def test_detail_renders_with_parties_and_amendment(self, client):
        client.force_login(UserFactory(is_superuser=True, is_staff=True))
        supplier = SupplierFactory(name="Acme")
        customer = _make_stakeholder(StakeholderCategory.CUSTOMERS)
        contract = ContractFactory(suppliers=[supplier], clients=[customer])
        ContractFactory(parent=contract, label="Avenant 1")
        resp = client.get(reverse("assets:contract-detail", kwargs={"pk": contract.pk}))
        assert resp.status_code == 200
        assert b"Acme" in resp.content
        assert b"Avenant 1" in resp.content
        # The lifecycle renders with the standardised directed-graph stepper.
        assert b"data-lc-edges" in resp.content


@pytest.mark.django_db
class TestContractDocumentDownload:
    def _contract_with_pdf(self, scope=None):
        c = ContractFactory(scopes=[scope] if scope else [])
        c.file_content = _PDF_BYTES
        c.file_name = "deal.pdf"
        c.content_type = "application/pdf"
        c.save()
        return c

    def test_download_requires_login(self, client):
        c = self._contract_with_pdf()
        resp = client.get(reverse("assets:contract-document", kwargs={"pk": c.pk}))
        assert resp.status_code == 302  # redirected to login

    def test_download_returns_pdf(self, client):
        client.force_login(UserFactory(is_superuser=True, is_staff=True))
        c = self._contract_with_pdf()
        resp = client.get(reverse("assets:contract-document", kwargs={"pk": c.pk}))
        assert resp.status_code == 200
        assert resp["Content-Type"] == "application/pdf"
        assert "deal.pdf" in resp["Content-Disposition"]
        assert resp.getvalue() == _PDF_BYTES

    def test_download_404_without_document(self, client):
        client.force_login(UserFactory(is_superuser=True, is_staff=True))
        c = ContractFactory()
        resp = client.get(reverse("assets:contract-document", kwargs={"pk": c.pk}))
        assert resp.status_code == 404

    def test_download_scope_restricted(self, client):
        from accounts.models import Group, Permission

        scope_a = ScopeFactory()
        scope_b = ScopeFactory()
        reader = UserFactory()
        grp = Group.objects.create(name="ScopedContractReaders")
        grp.permissions.add(Permission.objects.get(codename="assets.contract.read"))
        grp.allowed_scopes.add(scope_a)
        grp.users.add(reader)
        client.force_login(reader)

        in_scope = self._contract_with_pdf(scope=scope_a)
        out_scope = self._contract_with_pdf(scope=scope_b)
        assert client.get(reverse("assets:contract-document", kwargs={"pk": in_scope.pk})).status_code == 200
        assert client.get(reverse("assets:contract-document", kwargs={"pk": out_scope.pk})).status_code == 404


@pytest.mark.django_db
class TestContractAPI:
    def _client(self):
        from rest_framework.test import APIClient

        api = APIClient()
        api.force_authenticate(user=UserFactory(is_superuser=True))
        return api

    def test_api_create_and_list(self):
        api = self._client()
        scope = ScopeFactory()
        resp = api.post(
            "/api/v1/assets/contracts/",
            {"label": "API MSA", "status": "draft", "scopes": [str(scope.pk)]},
            format="json",
        )
        assert resp.status_code == 201, resp.json()
        data = _data(resp)
        assert data["reference"].startswith("CTRT-")
        # file_content bytes are never exposed
        assert "file_content" not in data

        listed = api.get("/api/v1/assets/contracts/")
        assert listed.status_code == 200

    def test_api_document_url_present_when_attached(self):
        api = self._client()
        c = ContractFactory()
        c.file_content = _PDF_BYTES
        c.file_name = "x.pdf"
        c.save()
        resp = api.get(f"/api/v1/assets/contracts/{c.pk}/")
        assert resp.status_code == 200
        assert _data(resp)["document_url"].endswith(f"/contracts/{c.pk}/document/")

    def test_api_filter_is_amendment(self):
        api = self._client()
        top = ContractFactory()
        ContractFactory(parent=top)
        resp = api.get("/api/v1/assets/contracts/?is_amendment=true")
        assert resp.status_code == 200


@pytest.mark.django_db
class TestContractMCPRegistered:
    def test_contract_tools_registered(self):
        from mcp.server import McpServer
        from mcp.tools import register_all_tools

        server = McpServer()
        register_all_tools(server)
        for name in ["list_contracts", "get_contract", "create_contract",
                     "update_contract", "delete_contract", "transition_contract",
                     "contract_allowed_transitions"]:
            assert name in server._tools


@pytest.mark.django_db
class TestContractHierarchyAndSupersede:
    def test_list_shows_amendments_nested(self, client):
        client.force_login(UserFactory(is_superuser=True, is_staff=True))
        parent = ContractFactory(reference="CTRT-100", label="Parent MSA")
        child = ContractFactory(reference="CTRT-101", label="Avenant 1", parent=parent)
        resp = client.get(reverse("assets:contract-list"))
        assert resp.status_code == 200
        rows = list(resp.context["contracts"])
        by_pk = {c.pk: c for c in rows}
        assert by_pk[parent.pk].tree_level == 0
        assert by_pk[child.pk].tree_level == 1
        # the amendment renders directly under its parent
        assert rows.index(by_pk[parent.pk]) + 1 == rows.index(by_pk[child.pk])

    def test_supersedes_relationship(self):
        old = ContractFactory()
        new = ContractFactory(supersedes=old)
        assert new.supersedes == old
        assert old.is_superseded is True
        assert new.is_superseded is False
        assert list(old.superseded_by.all()) == [new]

    def test_supersedes_set_null_on_replacement_delete(self):
        old = ContractFactory(status=ContractStatus.DRAFT)
        new = ContractFactory(status=ContractStatus.DRAFT, supersedes=old)
        old.delete()  # draft -> deletable; SET_NULL keeps the survivor
        new.refresh_from_db()
        assert new.supersedes is None

    def test_supersedes_queryset_excludes_self(self):
        c = ContractFactory()
        form = ContractCreateForm(user=UserFactory(is_superuser=True), instance=c)
        assert c not in list(form.fields["supersedes"].queryset)

    def test_detail_shows_supersede_both_directions(self, client):
        client.force_login(UserFactory(is_superuser=True, is_staff=True))
        old = ContractFactory(reference="CTRT-200", label="Old deal")
        new = ContractFactory(reference="CTRT-201", label="New deal", supersedes=old)
        resp_old = client.get(reverse("assets:contract-detail", kwargs={"pk": old.pk}))
        assert b"CTRT-201" in resp_old.content  # replaced by
        resp_new = client.get(reverse("assets:contract-detail", kwargs={"pk": new.pk}))
        assert b"CTRT-200" in resp_new.content  # cancels and replaces
