# Generated by Django 6.0.2 on 2026-06-02

"""Refresh Report.report_type choices to include the risk-register and ISO 27005 types.

The `risk_register` and `iso27005_report` values were added to the
`reports.constants.ReportType` enum (v0.23.0) and their generators
wired up, but no migration was generated to update the field choices
metadata. Every makemigrations dry-run kept flagging this as pending
and the warning surfaced at container boot. This migration captures
the AlterField so the diff is clean. Choices metadata only: no DB
schema change.
"""

from django.db import migrations, models


REPORT_TYPE_CHOICES = [
    ('soa', 'Statement of Applicability'),
    ('audit_report', 'Audit report'),
    ('management_review_pptx', 'Management review - Presentation'),
    ('management_review_docx', 'Management review - Minutes'),
    ('risk_register', 'Risk register'),
    ('iso27005_report', 'ISO 27005 risk assessment report'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_historicalreport_report_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreport',
            name='report_type',
            field=models.CharField(choices=REPORT_TYPE_CHOICES, max_length=30, verbose_name='Report type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=REPORT_TYPE_CHOICES, max_length=30, verbose_name='Report type'),
        ),
    ]
