# Generated by Django 6.0.6 on 2026-06-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_management_review_workflow_state_from_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmanagementreview',
            name='status',
        ),
        migrations.RemoveField(
            model_name='managementreview',
            name='status',
        ),
    ]
