# Generated by Django 6.0.6 on 2026-06-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_remove_historicalmanagementreview_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmanagementreview',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='historicalmanagementreview',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='historicalmanagementreview',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='managementreview',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='managementreview',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='managementreview',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='historicalmanagementreview',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AlterField(
            model_name='managementreview',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle.', max_length=32, verbose_name='Lifecycle state'),
        ),
    ]
