# Generated by Django 6.0.6 on 2026-06-13 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('question', models.TextField(verbose_name='Question')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='Interface language')),
                ('rating', models.CharField(choices=[('up', 'Thumbs up'), ('down', 'Thumbs down')], max_length=4, verbose_name='Rating')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('summary', models.TextField(blank=True, verbose_name='LLM summary')),
                ('results', models.JSONField(blank=True, default=list, verbose_name='Returned records')),
                ('degraded', models.BooleanField(default=False, verbose_name='Degraded answer')),
                ('refused_tools', models.JSONField(blank=True, default=list, verbose_name='Refused tools')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='LLM provider')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='LLM model')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_feedback', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Assistant feedback',
                'verbose_name_plural': 'Assistant feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rating', 'created_at'], name='assistant_a_rating_50e0a0_idx')],
            },
        ),
    ]
