# Generated by Django 6.0.6 on 2026-06-13 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_semanticindex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantfeedback',
            name='is_resolved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Corrected'),
        ),
        migrations.AddField(
            model_name='assistantfeedback',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Corrected at'),
        ),
        migrations.AddField(
            model_name='assistantfeedback',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_assistant_feedback', to=settings.AUTH_USER_MODEL, verbose_name='Corrected by'),
        ),
    ]
